### ISSUE TITLE
Extracting keywords and dependencies on keywords from query

### ISSUE THREAD

**Issue by helenmfoster** [kapil1garg/eecs338-chris-jones#12]

**Comment by ngparas** [comment]
This is overlapping a bit with the approach I'm taking to search for answer formulae, so I'm going to piggyback off of this and/or contribute if it works

Other issue link https://github.com/kapil1garg/eecs338-chris-jones/issues/20

**Comment by ngparas** [comment]
Can you add some functionality to do genre extraction, and then use the actors/shows/theaters from  https://github.com/kapil1garg/eecs338-chris-jones/issues/31 to augment our query tagging to aid in query routing in #20 ?

**Comment by ngparas** [comment]
good enough, mostly rolled into #20
