### ISSUE TITLE
Come up with 10 types of questions to ask

### ISSUE THREAD

**Issue by ngparas** [kapil1garg/eecs338-chris-jones#17]
Start question answer frameworks

**Comment by ngparas** [comment]
For Nick ->
(1) Cherry pick some answers for 'What is Good Acting' and then get a dummy version of that going
(2) What do you think of <play/show/...>?
(3) Time permitting (it totally wont before thursday), take a stab at genre questions

Aaand, write up the stuff on the Wiki to cover our approaches to these questions so we have some living documentation there.

**Comment by ngparas** [comment]
From our doc 'Possible Questions'

What do you think is good acting?
Entities: None
PRON VERB PRON VERB VERB ADJ NOUN PUNCT
Not too hot because it never identifies a subject. This would be a hard one for us.

I want to go to Second City. Do you think it’s good?
Entities: Second City (Location)
Do you think it 's good? -> VERB PRON VERB PRON VERB ADJ PUNCT
This one looks like we could do something like entity is adj? So like a sentiment analysis on his articles that mention Second City.

What did you think of Hamilton?
Entities: Hamilton (Person)
What did you think of Hamilton? -> PRON VERB PRON VERB ADP NOUN PUNCT
Again we could do sentiment analysis on any articles that contain Hamilton.

Do you think John Doe is a good actor?
Entities: John Doe (Person)
Do you think John Doe is a good actor? ->VERB PRON VERB NOUN NOUN VERB DET ADJ NOUN PUNCT

What is the best performance right now?
Entities: None
What is the best performance right now? -> PRON VERB DET ADJ NOUN ADV ADV PUNCT
This would be another tough one. I think we would aim to do something like look at his recent reviews and return the one with the highest rating. “Best” and “now” would be great words to focus on.

**Comment by kapil1garg** [comment]
@ngparas  will make the questions to claim on a google doc and then OPEN SEASON 🏹

**Comment by ngparas** [comment]
split into separate issues, closing
