### ISSUE TITLE
Query: Genre Aggregation

### ISSUE THREAD

**Issue by ngparas** [kapil1garg/eecs338-chris-jones#50]
How do you like your comedy?
How do you like your drama?
What do you think about tragedy?
How do you feel about musicals?
etc.

Please implement query, response-building logic if necessary, and then finally write up the approach on the wiki

Side note: One approach could be very similar to #47

**Comment by ngparas** [comment]
Also add do you have a favorite genre?

**Comment by kapil1garg** [comment]
Very basic approach...given a genre G:
1. Find all documents with that G mentioned
2. Aggregate sentiment across documents
3. Return sentiment only (don't try to find a representative sentence)
